language: c
compiler:
    - gcc
    - clang
script: make && make test
notifications:
    irc:
        channels:
            - "irc.freenode.org#gmqcc"
        template:
            - "[%{commit} : %{author}] %{message}"
            - "%{build_url}"
        skip_join: true
